export const OPEN_DELETE_WINDOW = 'OPEN_DELETE_WINDOW';
export const CLOSE_DELETE_WINDOW = 'CLOSE_DELETE_WINDOW';
export const OPEN_EDIT_WINDOW = 'OPEN_EDIT_WINDOW';
export const CLOSE_EDIT_WINDOW = 'CLOSE_EDIT_WINDOW';
