export const OPEN_DELETE_DIALOG = 'OPEN_DELETE_DIALOG';
export const CLOSE_DELETE_DIALOG = 'CLOSE_DELETE_DIALOG';
export const OPEN_EDIT_DIALOG = 'OPEN_EDIT_DIALOG';
export const CLOSE_EDIT_DIALOG = 'CLOSE_EDIT_DIALOG';
export const OPEN_ADD_DIALOG = 'OPEN_ADD_DIALOG';
export const CLOSE_ADD_DIALOG = 'CLOSE_ADD_DIALOG';

export const INPUT_RECIPE = 'INPUT_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';

export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
